### ISSUE TITLE
Web socket disconnecting after 2 days,    can we run only example.py --symbol for production

### ISSUE THREAD

**Issue by Pechi77** [philipperemy/bitmex-liquidations#3]
I ran the `example.py  XBTUSD` and see that the script stopped running after two days.

Error message:

```--- Logging error ---
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_app.py", line 278, in run_forever
    dispatcher.read(self.sock.sock, read)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_app.py", line 63, in read
    callback()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_app.py", line 251, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/datahub/src/indicators/bitmex-liquidations/bitmex_liquidation/api.py", line 111, in <lambda>
    self.wst = threading.Thread(target=lambda: self.ws.run_forever(ping_interval=5),
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_app.py", line 280, in run_forever
    self._callback(self.on_error, e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/websocket/_app.py", line 315, in _callback
    callback(self, *args)
  File "/home/ubuntu/datahub/src/indicators/bitmex-liquidations/bitmex_liquidation/api.py", line 147, in _on_error
    logger.info('on_error()', error)
Message: 'on_error()'
Arguments: (WebSocketConnectionClosedException('Connection is already closed.',),)
2020-04-14 23:05:13,037 - Websocket Closed
```

**Comment by philipperemy** [comment]
@Pechi77 hum probably bitmex closed the connection. A simple way is to catch this exception in on_error and restart the websocket. If you can make a quick PR, that'd be appreciated :)

**Comment by Pechi77** [comment]
@philipperemy Okay, thank you for your quick response :)

**Comment by Pechi77** [comment]
I am planning to run another corn job, whenever this goes down, restart with sub process, what do you think ?

**Comment by philipperemy** [comment]
@Pechi77 if you have a mechanism to detect when it drops, then it works too! Just make sure to kill the previous process before starting a new one. Otherwise bitmex might complain.

**Comment by Pechi77** [comment]
Okay
